---
- name: Install Java 8 using YUM.
  yum:
    name: "{{java.VERSION}}"
    state: latest
  become: true

- name: Download Jenkins repo yum URL for
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import GPG Key
  rpm_key:
    state: present
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
  become: yes
  become_user: root

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
  become: yes
  become_user: root

- name: Change Jenkins JAVA options
  lineinfile: dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{ jenkins.JAVA_OPTIONS }}"
  become: yes
  become_user: root

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes
  become: yes
  become_user: root
